/* ===== DATABASE LAYER: IndexedDB/cache + optional Supabase ===== */
const MLDatabase=(()=>{let database=null,databaseReady=false,users=new Map(),leaderboard=[];
const readJson=(k,d=null)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(e){return d}};
const writeJson=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const clone=v=>JSON.parse(JSON.stringify(v));
function remote(){const r=DATABASE_CONFIG.remote.supabase;return r&&r.url&&r.anonKey?r:null}
function headers(){return {'apikey':DATABASE_CONFIG.remote.supabase.anonKey,'Authorization':'Bearer '+DATABASE_CONFIG.remote.supabase.anonKey,'Content-Type':'application/json','Prefer':'resolution=merge-duplicates'}}
function getCachedUser(){const c=readJson(DATABASE_CONFIG.cache.user,null);if(c&&c._cacheExpiresAt&&c._cacheExpiresAt<Date.now())try{localStorage.removeItem(DATABASE_CONFIG.cache.user)}catch(e){}else if(c)return c;return readJson(DATABASE_CONFIG.legacy.user,null)}
function norm(e){return{uid:String(e.uid||''),name:String(e.name||'?'),characterIndex:Number(e.characterIndex??e.character_index??e.ch??0),score:Number(e.score||0),kills:Number(e.kills||0),night:Number(e.night||0),timestamp:Number(e.timestamp??e.timestamp_ms??e.t??Date.now()),roundId:String(e.roundId||e.round_id||tournamentRoundId())}}
function currentRoundOnly(arr){const round=tournamentRoundId();return (Array.isArray(arr)?arr:[]).filter(e=>norm(e).roundId===round).map(norm)}
function getCachedLeaderboard(){const c=readJson(DATABASE_CONFIG.cache.leaderboard,null),l=readJson(DATABASE_CONFIG.legacy.leaderboard,[]);return currentRoundOnly(Array.isArray(c)?c:l)}
function cacheUser(u){if(!u)return;writeJson(DATABASE_CONFIG.cache.user,Object.assign({},u,{_cacheExpiresAt:Date.now()+GAME_CONFIG.cache.profileTtlMs}));writeJson(DATABASE_CONFIG.cache.session,{uid:u.uid||'',expiresAt:Date.now()+GAME_CONFIG.cache.sessionTtlMs});writeJson(DATABASE_CONFIG.legacy.user,u)}
function cacheLeaderboard(a){const clean=currentRoundOnly(a).sort((a,b)=>b.score-a.score).slice(0,GAME_CONFIG.leaderboard.maxEntries);writeJson(DATABASE_CONFIG.cache.leaderboard,clean);writeJson(DATABASE_CONFIG.legacy.leaderboard,clean)}
function openDatabase(){return new Promise(resolve=>{if(!('indexedDB'in window))return resolve(null);let req;try{req=indexedDB.open(DATABASE_CONFIG.name,DATABASE_CONFIG.version)}catch(e){return resolve(null)}req.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('users'))db.createObjectStore('users',{keyPath:'uid'});if(!db.objectStoreNames.contains('leaderboard'))db.createObjectStore('leaderboard',{keyPath:'uid'})};req.onsuccess=e=>resolve(e.target.result);req.onerror=()=>resolve(null)})}
function readAll(store){return new Promise(resolve=>{if(!database)return resolve([]);try{const r=database.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>resolve([])}catch(e){resolve([])}})}
function saveStore(store,v){return new Promise(resolve=>{if(!database)return resolve(false);try{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(clone(v));tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false);tx.onabort=()=>resolve(false)}catch(e){resolve(false)}})}
async function remoteLeaderboard(){const r=remote();if(!r)return[];try{const q=`${r.url.replace(/\/$/,'')}/rest/v1/${r.leaderboardTable}?select=uid,name,character_index,score,kills,night,timestamp_ms,round_id&round_id=eq.${encodeURIComponent(tournamentRoundId())}&order=score.desc&limit=${GAME_CONFIG.leaderboard.maxEntries}`;const res=await fetch(q,{headers:headers()});if(!res.ok)return[];return currentRoundOnly(await res.json())}catch(e){return[]}}
async function remoteUpsert(e){const r=remote();if(!r)return false;try{const url=`${r.url.replace(/\/$/,'')}/rest/v1/${r.leaderboardTable}`;const body={uid:e.uid,name:e.name,character_index:e.characterIndex,score:e.score,kills:e.kills,night:e.night,timestamp_ms:e.timestamp,round_id:e.roundId};const res=await fetch(url,{method:'POST',headers:headers(),body:JSON.stringify(body)});return res.ok}catch(e){return false}}
async function init(){const cu=getCachedUser();leaderboard=getCachedLeaderboard();if(cu?.uid)users.set(String(cu.uid),clone(cu));database=await openDatabase();if(database){for(const u of await readAll('users'))if(u?.uid)users.set(String(u.uid),u);const sl=await readAll('leaderboard');if(sl.length)leaderboard=currentRoundOnly(sl);else if(leaderboard.length)for(const e of leaderboard)await saveStore('leaderboard',e)}const remoteLB=await remoteLeaderboard();if(remoteLB.length){leaderboard=remoteLB;for(const e of remoteLB)await saveStore('leaderboard',e)}cacheLeaderboard(leaderboard);if(cu?.uid&&users.has(String(cu.uid)))cacheUser(users.get(String(cu.uid)));databaseReady=true;return true}
function getCurrentUser(){const s=readJson(DATABASE_CONFIG.cache.session,null);if(s?.uid&&(!s.expiresAt||s.expiresAt>Date.now()))return clone(users.get(String(s.uid))||getCachedUser()||{});return clone(getCachedUser()||{})}
async function remoteUserUpsert(u){const r=remote();if(!r)return false;try{const url=`${r.url.replace(/\/$/,'')}/rest/v1/${r.usersTable}`;const body={uid:u.uid,name:u.name,character_index:u.characterIndex,best_score:u.bestScore,games_played:u.gamesPlayed,stats:u.stats||{},achievements:u.achievements||[],access_code:u.accessCode||null};const res=await fetch(url,{method:'POST',headers:headers(),body:JSON.stringify(body)});return res.ok}catch(e){return false}}
async function saveUser(u){if(!u?.uid)return null;users.set(String(u.uid),clone(u));cacheUser(u);await saveStore('users',u);void remoteUserUpsert(u);return clone(u)}
async function getUser(uid){if(!uid)return getCurrentUser();const id=String(uid);if(users.has(id))return clone(users.get(id));if(database)try{const u=await new Promise(resolve=>{const r=database.transaction('users','readonly').objectStore('users').get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>resolve(null)});if(u){users.set(id,u);cacheUser(u);return clone(u)}}catch(e){}return null}
async function refreshLeaderboard(){const r=await remoteLeaderboard();if(r.length){leaderboard=r.sort((a,b)=>b.score-a.score).slice(0,GAME_CONFIG.leaderboard.maxEntries);cacheLeaderboard(leaderboard);for(const e of leaderboard)await saveStore('leaderboard',e)}return clone(leaderboard)}
async function submitScore(e){if(!e?.uid)return;const n=norm(e),old=leaderboard.find(x=>x.uid===n.uid);if(old)Object.assign(old,n);else leaderboard.push(n);leaderboard=leaderboard.sort((a,b)=>b.score-a.score).slice(0,GAME_CONFIG.leaderboard.maxEntries);cacheLeaderboard(leaderboard);await saveStore('leaderboard',n);void remoteUpsert(n)}
return Object.freeze({init,ready:()=>databaseReady,getCachedUser,getCachedLeaderboard,getCurrentUser,currentUser:getCurrentUser,saveUser,createUser:saveUser,getUser,login:getUser,submitScore,getLeaderboardSync:()=>clone(leaderboard),getLeaderboard:async()=>clone(leaderboard),refreshLeaderboard,config:DATABASE_CONFIG})})();
