/* ===== SHOP + 30 SECOND EDUCATIONAL QUIZ ===== */
let shopQuiz={active:false,time:0,current:null,timer:0,answered:false};
const QUIZ=[
 ['12 + 8 = ?',20],['9 × 7 = ?',63],['100 ÷ 4 = ?',25],['15 + 27 = ?',42],['6 × 8 = ?',48],['90 - 37 = ?',53],
 ['3² + 4² = ?',25],['120 ÷ 10 = ?',12],['7 × 6 - 5 = ?',37],['50 + 25 - 10 = ?',65]
];
function shopOpen(){show('menu',0);show('shop',1);shopRender()}
function shopClose(){quizStop();show('shop',0);show('menu',1);S='menu';renderLB()}
function shopRender(){if(!$('#shop'))return;const swordCost=GAME_CONFIG.shop.swordBaseCost*(playerProfile.swordLevel+1),skillCost=GAME_CONFIG.shop.skillBaseCost*(playerProfile.skillLevel+1);$('#shopMoney').textContent=playerProfile.coins;$('#shopItems').innerHTML=`<div class="shop-item"><div class="shop-icon">⚔</div><div><b>${getCurrentCharacterClass().weapon}</b><small>Level ${playerProfile.swordLevel}/${GAME_CONFIG.shop.maxSwordLevel}<br>Serangan dasar +${playerProfile.swordLevel*10}%</small></div><button class="shop-buy b s" data-buy="sword" ${playerProfile.swordLevel>=GAME_CONFIG.shop.maxSwordLevel?'disabled':''}>${playerProfile.swordLevel>=GAME_CONFIG.shop.maxSwordLevel?'MAX':'BELI '+swordCost}</button></div><div class="shop-item"><div class="shop-icon">✦</div><div><b>${getCurrentCharacterClass().skillName}</b><small>Level ${playerProfile.skillLevel}/${GAME_CONFIG.shop.maxSkillLevel}<br>Efek skill +${playerProfile.skillLevel*12}%</small></div><button class="shop-buy b s" data-buy="skill" ${playerProfile.skillLevel>=GAME_CONFIG.shop.maxSkillLevel?'disabled':''}>${playerProfile.skillLevel>=GAME_CONFIG.shop.maxSkillLevel?'MAX':'BELI '+skillCost}</button></div>`}
function shopBuy(type){const level=type==='sword'?playerProfile.swordLevel:playerProfile.skillLevel,max=type==='sword'?GAME_CONFIG.shop.maxSwordLevel:GAME_CONFIG.shop.maxSkillLevel;if(level>=max){shopMessage('Level sudah maksimal.');return}const cost=(type==='sword'?GAME_CONFIG.shop.swordBaseCost:GAME_CONFIG.shop.skillBaseCost)*(level+1);if(playerProfile.coins<cost){shopMessage('Uang kamu belum cukup. Jawab soal untuk mendapat uang.');SFX.hurt();return}playerProfile.coins-=cost;if(type==='sword')playerProfile.swordLevel++;else playerProfile.skillLevel++;savePlayerProfile();SFX.lvl();shopMessage(type==='sword'?'Senjata berhasil ditingkatkan!':'Skill berhasil ditingkatkan!');shopRender()}
function shopMessage(text){const e=$('#shopMsg');if(e){e.textContent=text;e.classList.remove('flash');void e.offsetWidth;e.classList.add('flash')}}
function quizStart(){if(shopQuiz.active)return;shopQuiz={active:true,time:GAME_CONFIG.shop.quizSeconds,current:null,timer:0,answered:false};$('#quizPanel').classList.add('active');quizNext();shopTick()}
function quizStop(){shopQuiz.active=false;clearTimeout(shopQuiz.timer);$('#quizPanel')?.classList.remove('active')}
function quizNext(){const q=QUIZ[Math.floor(Math.random()*QUIZ.length)];shopQuiz.current=q;shopQuiz.answered=false;$('#quizQuestion').textContent=q[0];$('#quizAnswer').value='';$('#quizAnswer').focus();$('#quizResult').textContent='';$('#quizTime').textContent=shopQuiz.time+'s'}
function quizSubmit(){if(!shopQuiz.active||shopQuiz.answered)return;const ans=Number($('#quizAnswer').value);shopQuiz.answered=true;if(ans===shopQuiz.current[1]){addCoins(GAME_CONFIG.shop.correctReward);$('#quizResult').textContent=`BENAR! +${GAME_CONFIG.shop.correctReward} uang`;SFX.pick()}else{$('#quizResult').textContent=`SALAH. Jawaban: ${shopQuiz.current[1]}`;SFX.hurt()}setTimeout(()=>{if(shopQuiz.active&&shopQuiz.time>0)quizNext()},650)}
function shopTick(){if(!shopQuiz.active)return;$('#quizTime').textContent=shopQuiz.time+'s';if(shopQuiz.time<=0){shopQuiz.active=false;$('#quizResult').textContent='Waktu habis. Coba lagi untuk mendapatkan uang.';setTimeout(()=>$('#quizPanel').classList.remove('active'),1200);return}shopQuiz.timer=setTimeout(()=>{shopQuiz.time--;shopTick()},1000)}
document.addEventListener('click',e=>{if(e.target.closest?.('#shopCloseTop')){shopClose();return}if(e.target.closest?.('#quizCollapse')){const card=$('#quizPanel');card.classList.toggle('collapsed');e.target.textContent=card.classList.contains('collapsed')?'+ SOAL EDUKASI':'− SOAL EDUKASI';return}const buy=e.target.closest?.('.shop-buy');if(buy)shopBuy(buy.dataset.buy);if(e.target.closest?.('#quizStart'))quizStart();if(e.target.closest?.('#quizSubmit'))quizSubmit();if(e.target.closest?.('#quizClose'))quizStop()});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&shopQuiz.active)quizSubmit()});
